language: java
jdk:
  - oraclejdk8
addons:
   sonarcloud:
       organization: "sweiws2017_18"
       branches:
       - master
       - sprint-2
install: true
script:
  mvn -Ptravis clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
