spring:
  profiles: default
  # H2
  h2:
    console.enabled: true
    console.path: /h2
  # Datasource
  datasource:
    url: jdbc:h2:file:./test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa.hibernate.ddl-auto: create

email.name: "activity.meterhm@gmail.com"
email.password: "holzwurm3"
host.url: "http://www.localhost:8080"

---

spring:
  profiles: prod
  datasource:
    url: jdbc:${DATABASE_URL}
  jpa.hibernate.ddl-auto: validate

---